### ISSUE TITLE
Positioning Glitch On Orders Page

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#26]
![employee repair orders_](https://cloud.githubusercontent.com/assets/5702426/21741501/aed3fb22-d4cf-11e6-96ee-5d8fa65eb502.png)

**Comment by jcergolj** [comment]
Is this something that happens before page is fully loaded?

**Comment by Samyoul** [comment]
No it happens on a fully loaded page. I think it has something to do with its CSS:

``` css
.additional_table_field {
    position: absolute;
    top: 18px;
    right: 0;
    font-weight: 700;
    white-space: nowrap;
}
```
